const Images = [
    { idx: 1, img: 'https://i.imgur.com/utQI071.png', title: 'BenQ Zowie G-SR Large', desc: 'Big mousepad good', link: 'https://www.amazon.com/Zowie-Large-Gaming-Mouse-G-SR/dp/B00T56XWZU/ref=sr_1_1?dchild=1&keywords=zowie+gsr&qid=1615057260&sr=8-1', type: 'per' },
    { idx: 2, img: 'https://i.imgur.com/jakyI1F.png', title: 'Rosewill Green 630 Watt', link: 'https://www.newegg.com/rosewill-green-series-rg630-s12-continuous-630w-40-c/p/N82E16817182200', type: 'comp', desc: 'Power good' },
    { idx: 3, img: 'https://i.imgur.com/HmfL7Xe.png', title: 'Apple MacBook Pro (13-inch, M1, 2020, 16GB RAM)', link: 'https://www.apple.com/shop/buy-mac/macbook-pro/13-inch-space-gray-apple-m1-chip-with-8-core-cpu-and-8-core-gpu-256gb', type: 'mac', desc: 'Powerful laptop for mobility, mobile app design, and separation of work and gaming' },
    { idx: 4, img: 'https://i.imgur.com/SqaUefv.png', title: 'Logitech G Pro Wireless', link: 'https://www.amazon.com/Logitech-Wireless-Gaming-Esports-Performance/dp/B07GCKQD77/ref=sr_1_3?dchild=1&keywords=logitech+g+pro+wireless&qid=1615057192&s=electronics&sr=1-3', type: 'per', desc: 'Best sensor on the market, preferable small size and ambidextrous design, + wireless = yes' },
    {
        idx: 5, img: 'https://i.imgur.com/TEyV6Qs.png', title: 'Samsung 970 EVO NVMe M.2 SSD 500GB', link: 'https://www.amazon.com/Samsung-970-EVO-500GB-MZ-V7E500BW/dp/B07BN4NJ2J/ref=sr_1_1?dchild=1&keywords=samsung+970+evo+500gb+m.2&qid=1615057025&sr=8-1', type: 'comp', desc: 'Makes file loading extremely fast. 500GB is all I need for games'
    },
    { idx: 6, img: 'https://i.imgur.com/bwXvxNU.png', title: 'ASUS VG248QE 24" 144Hz', link: 'https://www.amazon.com/ASUS-VG248QE-1920x1080-Gaming-Monitor/dp/B00B2HH7G0', type: 'per', desc: '24 inch, 1080p, 144Hz+ are the ideal specs for a gaming monitor. Have used this for like 8 years now.' },
    { idx: 7, img: 'https://i.imgur.com/Zriw14b.png', title: 'Samsung 860 EVO 120GB SSD', link: 'https://www.amazon.com/Samsung-500GB-Internal-MZ-76E500B-AM/dp/B0781Z7Y3S/ref=sr_1_3?dchild=1&keywords=samsung+860+evo+500gb&qid=1615057011&sr=8-3', type: 'comp', desc: 'Fast enough SSD where I archive windows optimization programs/setup and config files' },
    { idx: 8, img: 'https://i.imgur.com/5QwCDEs.png', title: 'NZXT Source 210 ATX Mid Tower', link: 'https://www.newegg.com/black-nzxt-source-210-atx-mid-tower/p/N82E16811146102', type: 'comp', desc: 'Bought this case ages ago, it does the job' },
    { idx: 9, img: 'https://i.imgur.com/4gUcCCI.png', title: 'Apple Magic Keyboard, White', link: 'https://www.amazon.com/Apple-Keyboard-Wireless-Rechargable-English/dp/B016QO64FI/ref=sr_1_6?dchild=1&keywords=apple+magic+keyboard&qid=1615057298&sr=8-6', type: 'mac', desc: 'Great keyboard, Wireless comes in handy. I use this in clamshell mode with my macbook' },
    { idx: 10, img: 'https://i.imgur.com/haThWWm.png', title: 'Audio Technica AT-2020 Condensor Mic', link: 'https://www.amazon.com/Audio-Technica-AT2020-Cardioid-Condenser-Microphone/dp/B0006H92QK/ref=sr_1_1?dchild=1&keywords=audio+technica+at-2020&qid=1615057215&s=electronics&sr=1-1', type: 'audio', desc: 'Very good price to performance ratio' },
    { idx: 11, img: 'https://i.imgur.com/csQj1V7.png', title: 'Behringer Xenyx Q802', link: 'https://www.amazon.com/Behringer-Premium-Balanced-Windscreen-Reusable/dp/B085PT2744/ref=sr_1_2?dchild=1&keywords=behringer+q802usb&qid=1615699166&sr=8-2', type: 'audio', desc: 'Needed phantom power for the mic and this mixer provides it.' },
    { idx: 12, img: 'https://i.imgur.com/tKHzzQy.png', title: 'EVGA GeForce GTX 1080Ti SC Black Edition', link: 'https://www.amazon.com/EVGA-Optimized-Interlaced-Graphics-11G-P4-6393-KR/dp/B06Y11DFZ3?th=1', type: 'comp', desc: 'Bought this when it was the flagship, Great card, Probably wont have to upgrade for a while.' },
    { idx: 13, img: 'https://i.imgur.com/lQlySm0.png', title: "Sennheiser HD650", link: 'https://www.amazon.com/Sennheiser-HD-650-Professional-Headphone/dp/B00018MSNI/ref=sr_1_1?dchild=1&keywords=hd650&qid=1615056844&sr=8-1', type: 'audio', desc: 'These cans literally changed music for me. I cant go back and I want to spend like 3k more on audio' },
    { idx: 14, img: 'https://i.imgur.com/KuH8zE5.png', title: 'Kingston HyperX Alloy FPS Blues', link: 'https://www.amazon.com/HyperX-Alloy-FPS-Pro-Ultra-Compact/dp/B074F5L8GQ/ref=sr_1_1?dchild=1&keywords=kingston+hyperx+alloy+fps&qid=1615057183&s=electronics&sr=1-1', type: 'per', desc: 'Love the clickity clackity Blue switches, TKL is prefered by many but not me' },
    { idx: 15, img: 'https://i.imgur.com/Ty3lIBa.png', title: 'ASUS Prime Z270-A ATX', link: 'https://www.asus.com/us/Motherboards-Components/Motherboards/All-series/PRIME-Z270-A/', type: 'comp', desc: 'Just an average mobo' },
    { idx: 16, img: 'https://i.imgur.com/5rqbPHM.png', title: 'Hyper 212 EVO CPU Cooler', link: 'https://www.amazon.com/Cooler-Master-Hyper-Direct-Contact/dp/B005O65JXI/ref=sr_1_2?dchild=1&keywords=Hyper+212+Evo&qid=1615056910&sr=8-2)', type: 'comp', desc: 'Needed a cooler and this one is very popular cause its cheap' },
    { idx: 17, img: 'https://i.imgur.com/ACRqhe7.png', title: 'Intel® Core™ i7-7700K Processor', link: 'https://www.amazon.com/Intel-i7-7700K-Desktop-Processor-unlocked/dp/B01MXSI216/ref=sr_1_1_mod_primary_new?dchild=1&keywords=7700k&qid=1615056896&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sr=8-1', type: 'comp', desc: 'Solid processor for its time, would love to upgrade to the newest flagshop though' },
    { idx: 18, img: 'https://i.imgur.com/o8IjAXa.png', title: 'Aune X1S DAC/AMP', link: 'https://www.amazon.com/Aune-X1S-384KHz-Headphone-Amplifier/dp/B014FBZCCA/ref=sr_1_1?dchild=1&keywords=aune+x1s&qid=1615057201&s=electronics&sr=1-1', type: 'audio', desc: 'Great price to performance ratio, Can turn it all the way up with no distortion, plenty of power even for a 300ohm headphone' },
    { idx: 19, img: 'https://i.imgur.com/oRz1AcA.png', title: 'ASUS PG279QZ 27" 1440p 165Hz IPS', link: 'https://www.amazon.com/PG279Q-2560x1440-Monitor-Certified-Refurbished/dp/B07GWD3ZQL/ref=sr_1_2?dchild=1&keywords=asus+rog+swift+pg279qz+27+1440p+165hz&qid=1615057168&s=electronics&sr=1-2', type: 'per', desc: 'Really great monitor, great colors and size for productivity, could probably be replaced by a 32" OLED' },
    { idx: 20, img: 'https://i.imgur.com/PaR2Khy.png', title: 'G.SKILL 16GB (2 x 8GB) Ripjaws V Series DDR4 2400MHz', link: 'https://www.amazon.com/G-Skill-RipJaws-PC4-28800-CL16-19-19-39-F4-3600C16D-16GVKC/dp/B07X8DVDZZ/ref=sr_1_1?dchild=1&keywords=gskill+ripjaws+16gb&qid=1615056955&sr=8-1', type: 'comp', desc: 'Decent ram, I definitely want to upgrade to 4k+ MHZ and maybe 32GB cause why not' },
    {
        idx: 21, img: 'https://i.imgur.com/hJm3CNo.png', title: 'Western Digital Blue 2TB', link: 'https://www.amazon.com/WD-Blue-2TB-Hard-Drive/dp/B07JC1TQ7N/ref=sr_1_1?dchild=1&keywords=western+digital+blue+2tb&qid=1615056984&sr=8-1', type: 'comp', desc: 'I use this 2TB hard drive to store all my games where I dont care about performance, cause im too broke for an SSD'
    },
    {
        idx: 22, img: 'https://i.imgur.com/Wa1KtOa.png', title: 'Toshiba Canvio Flex 4TB Portable External Hard Drive USB-C', link: 'https://www.amazon.com/Toshiba-Canvio-Portable-External-HDTB440XK3CA/dp/B08DDC36S1/ref=sr_1_4?dchild=1&keywords=toshiba%2B4tb%2Bexternal%2Bhard%2Bdrive&qid=1615788586&sr=8-4&th=1', type: 'mac', desc: 'Used to store movies/shows locally, portability is very nice, USB-C and USB3.0 along with exFAT is very handy for Mac/Windows cross-platforming'
    }
];

export default Images